version: "3"
services:
  ms-sql-server:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ms-sql:/var/opt/mssql/data
  playboardgame:
    build:
      context: ./PlayBoardGame
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - gamePictures: ./playBoardGame/wwwroot/gamephotos
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: "Docker"
      DBServer: "ms-sql-server"
      DBPort: "1433"
      DBUser: "SA"
      DBPassword: ${SA_PASSWORD}
      DBDatabase: "PlayBoardGame"
      GoogleClientId: ${GOOGLE_CLIENT_ID}
      GoogleClientSecret: ${GOOGLE_CLIENT_SECRET}
      SendGridKey: ${SENDGRID_KEY}
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - playboardgame
volumes:
  ms-sql:
  gamePictures: