
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.UserController.UserProfileAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.UserController.UserProfileAsync(PlayBoardGame.Models.ViewModels.UserProfileViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.AccountController.RegisterAsync(PlayBoardGame.Models.ViewModels.RegisterViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.AccountController.LoginAsync(PlayBoardGame.Models.ViewModels.LoginViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.AccountController.LogoutAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.AccountController.SendResetPasswordLinkAsync(PlayBoardGame.Models.ViewModels.SendResetPasswordLinkViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.AccountController.ResetPasswordAsync(PlayBoardGame.Models.ViewModels.ResetPasswordViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Controllers.UserController.ChangePasswordAsync(PlayBoardGame.Models.ViewModels.ChangePasswordViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Models.SeedData.EnsurePopulatedAsync(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Email.SendGrid.SendGridEmailSender.SendEmailAsync(PlayBoardGame.Email.SendGrid.SendEmailDetails)~System.Threading.Tasks.Task{PlayBoardGame.Email.SendGrid.SendEmailResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Email.Template.EmailTemplateSender.SendGeneralEmailAsync(PlayBoardGame.Email.SendGrid.SendEmailDetails,System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{PlayBoardGame.Email.SendGrid.SendEmailResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Infrastructure.ContextProvider.GetCurrentUserId~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "<Pending>", Scope = "member", Target = "~M:PlayBoardGame.Infrastructure.ContextProvider.GetCurrentUser~System.Threading.Tasks.Task{PlayBoardGame.Models.AppUser}")]

